
#############
# Cpsc-3220 #
# Project 4 #
# Zice Wei  #
# C73880993 #
#############

#instruction:1.make
#            2. ./a.out -v < trace
#             a trace file and pagging.cfg file required.

CC=gcc
flag=Wall

BINS=a.out


paging: paging.c
	gcc -Wall paging.c -std=c99


clean:
	rm $(BINS)
